// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsbcQncQ74SKdp66nT3AWz4lph_X8BPk0',
    appId: '1:483353229946:web:161d2e48e54f4f258359c3',
    messagingSenderId: '483353229946',
    projectId: 'aihealthcompanion-ac088',
    authDomain: 'aihealthcompanion-ac088.firebaseapp.com',
    storageBucket: 'aihealthcompanion-ac088.firebasestorage.app',
    measurementId: 'G-2E7Y1J1EEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg7BYN90havWITV6S5wSKaPa6HRduDYak',
    appId: '1:483353229946:android:e6bebc5c426109c28359c3',
    messagingSenderId: '483353229946',
    projectId: 'aihealthcompanion-ac088',
    storageBucket: 'aihealthcompanion-ac088.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANgRbyekytuF7t0Q-A4RsEu4Ai3DvFFX8',
    appId: '1:483353229946:ios:9f06109324d1741f8359c3',
    messagingSenderId: '483353229946',
    projectId: 'aihealthcompanion-ac088',
    storageBucket: 'aihealthcompanion-ac088.firebasestorage.app',
    iosBundleId: 'com.example.aiHealthcompanionUsingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANgRbyekytuF7t0Q-A4RsEu4Ai3DvFFX8',
    appId: '1:483353229946:ios:9f06109324d1741f8359c3',
    messagingSenderId: '483353229946',
    projectId: 'aihealthcompanion-ac088',
    storageBucket: 'aihealthcompanion-ac088.firebasestorage.app',
    iosBundleId: 'com.example.aiHealthcompanionUsingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsbcQncQ74SKdp66nT3AWz4lph_X8BPk0',
    appId: '1:483353229946:web:989120307c4dfbbd8359c3',
    messagingSenderId: '483353229946',
    projectId: 'aihealthcompanion-ac088',
    authDomain: 'aihealthcompanion-ac088.firebaseapp.com',
    storageBucket: 'aihealthcompanion-ac088.firebasestorage.app',
    measurementId: 'G-RYN45QJ951',
  );
}
